// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLazjLA2huAHIk-asYiDrgkquDdCsd0Bk',
    appId: '1:172443881158:web:4730d93af023e0b70051c7',
    messagingSenderId: '172443881158',
    projectId: 'ostad-3223a',
    authDomain: 'ostad-3223a.firebaseapp.com',
    storageBucket: 'ostad-3223a.appspot.com',
    measurementId: 'G-MMT63GB7H0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhg4o35U2x4JxqiwSRaIolX5vxGMiP-rs',
    appId: '1:172443881158:android:4952bba4bf5f758a0051c7',
    messagingSenderId: '172443881158',
    projectId: 'ostad-3223a',
    storageBucket: 'ostad-3223a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH-ckFISsVKesSPyD_felikq1yngffrpw',
    appId: '1:172443881158:ios:019400ec5760dc810051c7',
    messagingSenderId: '172443881158',
    projectId: 'ostad-3223a',
    storageBucket: 'ostad-3223a.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH-ckFISsVKesSPyD_felikq1yngffrpw',
    appId: '1:172443881158:ios:019400ec5760dc810051c7',
    messagingSenderId: '172443881158',
    projectId: 'ostad-3223a',
    storageBucket: 'ostad-3223a.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLazjLA2huAHIk-asYiDrgkquDdCsd0Bk',
    appId: '1:172443881158:web:767cd361e3cd60f60051c7',
    messagingSenderId: '172443881158',
    projectId: 'ostad-3223a',
    authDomain: 'ostad-3223a.firebaseapp.com',
    storageBucket: 'ostad-3223a.appspot.com',
    measurementId: 'G-Y74MZMR2DF',
  );
}
